__which_function

diff --git a/bash_mybash b/bash_mybash
--- a/bash_mybash
+++ b/bash_mybash
@@ -17,11 +17,12 @@ __get_script_dir() {
 }
 
 __which_content() {
-    if [[ "$#" -ne 1 ]]; then
-        echo "usage: ${FUNCNAME[0]} <function_name>"
+    funcname=$1
+    which "${funcname}" > /dev/null 2>&1
+    if [[ "$?" != 0  ]]; then
+        echo "Error: \"${funcname}\" function not found."
         return 1
     fi
-    funcname=$1
     which "${funcname}" | sed -e '1,2d' | head -n -1 | awk '{$1=$1};1'
 }
 
